// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRgVzdZq5AyL3j7BlXovPdEk50mdwinzw',
    appId: '1:677876579874:web:fdf53c922190e76d64947b',
    messagingSenderId: '677876579874',
    projectId: 'fir-notes-860b3',
    authDomain: 'fir-notes-860b3.firebaseapp.com',
    storageBucket: 'fir-notes-860b3.appspot.com',
    measurementId: 'G-0HV0C9MMWQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtn_5fW-U4XMdQ1U6whEs7IVNX8TnO5iM',
    appId: '1:677876579874:android:9129f2197aa7568b64947b',
    messagingSenderId: '677876579874',
    projectId: 'fir-notes-860b3',
    storageBucket: 'fir-notes-860b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSailoLSpmr_54_KOvj8_vZRJEDxv0qLY',
    appId: '1:677876579874:ios:ea91ef39262f625f64947b',
    messagingSenderId: '677876579874',
    projectId: 'fir-notes-860b3',
    storageBucket: 'fir-notes-860b3.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRgVzdZq5AyL3j7BlXovPdEk50mdwinzw',
    appId: '1:677876579874:web:89841e3fb1a04b8e64947b',
    messagingSenderId: '677876579874',
    projectId: 'fir-notes-860b3',
    authDomain: 'fir-notes-860b3.firebaseapp.com',
    storageBucket: 'fir-notes-860b3.appspot.com',
    measurementId: 'G-50G5EKEQ7G',
  );
}
